docs: modified documentation to make it more clear
konstruktoid/hardening pull request #449
Opened 2024-07-09 12:26 UTC by taragurung

The error message was not clear while running the bash script to modified the documentation steps

2024-07-09 21:34 UTC, konstruktoid requested changes

2024-07-09 21:34 UTC, konstruktoid commented on README.adoc
> +. Change the configuration options in the `ubuntu.cfg` file. Make sure to update `CHANGEME=''` config else you will get the error message `Please read the code. Exiting`
my suggestion is  to shorten it abit.
"Make sure to update the `CHANGEME` variable otherwise the script will fail."

2024-07-10 03:11 UTC, taragurung commented on README.adoc
> +. Change the configuration options in the `ubuntu.cfg` file. Make sure to update `CHANGEME=''` config else you will get the error message `Please read the code. Exiting`
Done!

2024-07-10 12:18 UTC, konstruktoid approved these changes

2024-07-10 12:21 UTC, merged

2024-07-10 12:21 UTC, konstruktoid commented
Thanks @taragurung