For ubuntu-22.04 the script to delete users was not working so, versi…
konstruktoid/hardening pull request #450
Opened 2024-07-09 13:15 UTC by taragurung

1. user delete script was not working
2. added deletion script with version check, for Ubuntu:22.04 added new code to work for other version the previous code will run as it is.

Not sure if its an issue in other version but for Ubuntu:22.04 it will work

2024-07-09 21:32 UTC, konstruktoid requested changes

2024-07-09 21:32 UTC, konstruktoid commented on scripts/users
> +    sudo userdel -r "$user" 2> /dev/null
no need for `sudo`, the script is intended to run as `root`.

2024-07-09 21:32 UTC, konstruktoid commented on scripts/users
> +SCRIPT_COUNT=1
this shouldn't be here, `SCRIPT_COUNT` should be placed inside the functions and is started at https://github.com/konstruktoid/hardening/blob/master/scripts/pre#L4

2024-07-09 21:32 UTC, konstruktoid commented on scripts/users
> +if lsb_release -d | grep -q "Ubuntu 22.04"; then
don't limit to one release.

2024-07-09 21:36 UTC, konstruktoid commented
and correct the ShellCheck issue:
`scripts/users:23:12: note: Check exit code directly with e.g. 'if mycmd;', not indirectly with $?. [SC2181]`
https://github.com/konstruktoid/hardening/actions/runs/9857792141/job/27239466727

2024-07-10 03:09 UTC, taragurung commented on scripts/users
> +if lsb_release -d | grep -q "Ubuntu 22.04"; then
makes sense, i was not sure how it will behave in other release so added it. but will make changes

2024-07-10 12:20 UTC, konstruktoid requested changes

2024-07-10 12:20 UTC, konstruktoid commented on scripts/users
> +  SCRIPT_COUNT=1
Don't set a static `SCRIPT_COUNT`.

2024-07-10 16:01 UTC, taragurung commented on scripts/users
> +  SCRIPT_COUNT=1
necessary change done and checks passed! @konstruktoid

2024-07-10 16:05 UTC, taragurung commented on scripts/users
> +    sudo userdel -r "$user" 2> /dev/null
The documentation says `sudo bash ubuntu.sh` so might be the reason why it failed for me and had to add there.

2024-07-10 17:28 UTC, konstruktoid requested changes

2024-07-10 17:28 UTC, konstruktoid commented on scripts/users
> +  SCRIPT_COUNT=1
This one as well

2024-07-11 03:06 UTC, taragurung commented on scripts/users
> +  SCRIPT_COUNT=1
done!

2024-07-11 06:25 UTC, konstruktoid approved these changes

2024-07-11 06:27 UTC, konstruktoid requested changes

2024-07-11 06:27 UTC, konstruktoid commented on scripts/users
> +  for user in games gnats irc list news sync uucp; do
Not much left of this PR, what happened to the `pkill` and test?

2024-07-12 16:46 UTC, closed without merging