Psad add updated to new master
konstruktoid/hardening pull request #71
Opened 2020-05-31 11:43 UTC by hellresistor

31-5-2020 master code updated.
Allow maintener edits.

2020-05-31 22:21 UTC, hellresistor commented
WOW Verified many iisues! not good yet

2020-06-01 07:21 UTC, konstruktoid commented
Not good yet? Poke me when you want a review.

2020-06-01 17:19 UTC, hellresistor commented
i think do a mess when re-branching... i try resolve it github desktop offline mode first. sorry man. helps just matters :P

2020-06-01 18:43 UTC, konstruktoid commented
No worries, you're putting a lot of work in and we're doing this together.
I think `f_psad` should be placed as soon as possible after the firewall setup.

2020-06-01 18:55 UTC, hellresistor commented
> 
> 
> No worries, you're putting a lot of work in and we're doing this together.
> I think `f_psad` should be placed as soon as possible after the firewall setup.
Well if i put  on that place. i will get this

```
[3] Enable psad
/etc/psad/psad.conf does not exist.
psad package is not installed.
[3] Disable misc network 
```
Will install later. maybe after the 'f_package_install' function?

2020-06-02 14:13 UTC, konstruktoid commented
Yeah, it should be after the `f_package_install` function, since it install `psad`.

2020-06-03 06:41 UTC, konstruktoid commented on misc/suid.list
> +ip6tables
Why add these to the `suid.list`?

2020-06-03 06:42 UTC, konstruktoid commented on scripts/17_packages
> +    PACKAGE_INSTALL="acct aide-common apt-config-auto-update debsums gnupg2 haveged iptables-persistent libpam-cracklib libpam-tmpdir needrestart netfilter-persistent openssh-server postfix psad rkhu
Why `apt-config-auto-update`?

2020-06-03 06:44 UTC, konstruktoid commented on ubuntu.sh
> +    REQUIREDPROGS='arp w'
`arp` and `w` isn't available as Ubuntu .debs

2020-06-03 19:26 UTC, hellresistor commented on scripts/17_packages
> +    PACKAGE_INSTALL="acct aide-common apt-config-auto-update debsums gnupg2 haveged iptables-persistent libpam-cracklib libpam-tmpdir needrestart netfilter-persistent openssh-server postfix psad rkhu
same packages different type distro!

2020-06-03 19:28 UTC, hellresistor commented on misc/suid.list
> +ip6tables
just dont know if needed. because of ip6tables-restore

Well. what is this file on reality?

2020-06-03 19:34 UTC, hellresistor commented on ubuntu.sh
> +    REQUIREDPROGS='arp w'
oohh sorry. seems get been installed!! correcting

2020-06-04 07:14 UTC, konstruktoid commented on misc/suid.list
> +ip6tables
it says https://gtfobins.github.io/#+suid at the top

2020-06-04 16:46 UTC, hellresistor commented on misc/suid.list
> +ip6tables
Because is needed of psad log ipv6 logs

2020-06-04 19:31 UTC, hellresistor commented on misc/suid.list
> +ip6tables
have been checked. will be used BEFORE f_suid ! 
I will remove ip*tables .

2020-06-08 17:29 UTC, hellresistor commented
stuck here , after 'done' (ssh and cli)

```
[53] Post Processing
..
...
done

```

2020-06-13 08:57 UTC, hellresistor commented
@konstruktoid 
the $FW_ADMIN with AUTOFIL=Y

`  echo "$FW_ADMIN    0;" >> "$PSADDL"`
sent to file 2 ips. (dont know if my installation issue) can you test it?
`192.168.1.102 127.0.0.1     0;`
should be:
`192.168.1.102     0;`

*PS: you will loose ssh connection if this line will be wrong

2020-06-14 18:29 UTC, konstruktoid commented
`sed -i "s/FW_ADMIN='/FW_ADMIN='$ADMINIP /" ./ubuntu.cfg`  at https://github.com/konstruktoid/hardening/blob/master/ubuntu.sh#L53 will append `$ADMINIP` to `FW_ADMIN='127.0.0.1'` so we can safe bet the rules (https://github.com/konstruktoid/hardening/blob/master/ubuntu.cfg#L1).

2020-06-15 18:47 UTC, hellresistor commented
Yes, I understand that.
Check the next commit (in seconds).
Is not "respecting" your codeformat.

2020-06-16 22:30 UTC, hellresistor commented
Into VM. (not ssh connection).

still get the stuck..
![stucking](https://user-images.githubusercontent.com/50468493/84834499-67369700-b029-11ea-9dd2-ef3d939dc31c.png)

2020-06-17 08:00 UTC, konstruktoid commented
Doesn't https://github.com/konstruktoid/hardening/pull/71/commits/ef9ac05e1f062f44ae37463fa936ad3794ae3173#diff-31d3c16309f07f7c26b79278d1403afaR15 work?

2020-06-18 18:06 UTC, hellresistor commented
> Doesn't [ef9ac05#diff-31d3c16309f07f7c26b79278d1403afaR15](https://github.com/konstruktoid/hardening/commit/ef9ac05e1f062f44ae37463fa936ad3794ae3173#diff-31d3c16309f07f7c26b79278d1403afaR15) work?

yes work. resolve with that.

2020-06-22 06:54 UTC, konstruktoid commented
Yeah, but I can't really help without logs.

2020-06-22 19:34 UTC, hellresistor commented
Cleaned installation on ubuntu 20.
[hardening-testubuntu20-200622.log](https://github.com/konstruktoid/hardening/files/4815196/hardening-testubuntu20-200622.log)
[syslog.log](https://github.com/konstruktoid/hardening/files/4815215/syslog.log)

2020-06-25 20:28 UTC, hellresistor commented
@konstruktoid well. 

It is normal "stuck" when get this line. 
```
done
*** System restart required ***
```

should finish script sucefully?

2020-06-26 07:56 UTC, konstruktoid commented
Both are valid last log lines, `f_post` just updates grub silently unless verbose mode and `f_checkreboot` only prints a message if the server needs a reboot.

```
[...]
File updated: searched for 179 files, found 137
(Reading database ... 66857 files and directories currently installed.)
Purging configuration files for secureboot-db (1.5) ...
[ Rootkit Hunter version 1.4.6 ]
File updated: searched for 179 files, found 137
[51] Post processing

~/hardening$
```

```
  echo "[$SCRIPT_COUNT] Post processing"

  if [[ $VERBOSE == "Y" ]]; then
    update-grub
    ((SCRIPT_COUNT++))
  else
    update-grub 2>/dev/null
  fi

  find /boot/ -type f -name '*.cfg' -exec chmod 0400 {} \;
```

2020-09-28 11:27 UTC, konstruktoid commented
Needs a rebase.

2020-10-07 11:19 UTC, konstruktoid commented on README.adoc
> -[source,shell]
This part about `snap` is missing.

2020-10-07 11:19 UTC, konstruktoid commented on README.adoc
> +MYEMAIL="Your@mail.Only" // <13>
Does it have to be a valid email, and not just root?

2020-10-07 11:20 UTC, konstruktoid commented on README.adoc
> +RHEL-07-040520
`RHEL-07-040520` et al has been removed

2020-10-07 11:22 UTC, konstruktoid commented on README.adoc
> +`libpam-apparmor` `libpam-cracklib` `libpam-pwquality` `libpam-tmpdir` `needrestart`
`libpam-cracklib` was removed in e7f6712cb1fbc63a8c96e345715322aa64ff3f19

2020-10-07 11:22 UTC, konstruktoid commented on misc/logrotate.conf
> +/var/log/syslog {
why is this added?

2020-10-07 11:23 UTC, konstruktoid commented on scripts/17_packages
> +  elif grep -qi 'Debian' "/etc/os-release"; then
why are you supporting debian here?

2020-10-07 11:24 UTC, konstruktoid commented on scripts/18_sshdconfig
> +  ((SCRIPT_COUNT++))
fix needed, but not relevant to this PR.

2020-10-07 11:25 UTC, konstruktoid commented on tests/44_psad.bats
> +@test "Verify PSAD is installed" {
duplicate,  tests/17_packages.bats

2020-10-07 11:27 UTC, konstruktoid commented on ubuntu.sh
> +  for pre_require in $REQUIREDPROGS; do
This will fail since you define `$REQUIREDPROGS` only if `grep -qi 'Debian' "/etc/os-release"`.
Why add Debian?

2020-10-07 11:28 UTC, konstruktoid commented on ubuntu.sh
> +    if ! command -v "$pre_require" >/dev/null 2>&1; then
This will fail since `net-tools` and `procps` isn't the tools required but the packages they are available in.

2020-10-07 11:29 UTC, konstruktoid requested changes
See comments, still not possible to merge.

2020-10-07 11:42 UTC, hellresistor commented on README.adoc
> +MYEMAIL="Your@mail.Only" // <13>
well, should be a out-mail to PSAD can able send messages. maybe try put `root@localhost` ?

2020-10-07 11:46 UTC, hellresistor commented on misc/logrotate.conf
> +/var/log/syslog {
That was to logrotate logs to PSAD-iptables

2020-10-07 11:47 UTC, hellresistor commented on scripts/17_packages
> +  elif grep -qi 'Debian' "/etc/os-release"; then
well seems Ubuntu and Debian have similiar configurations, I think was good add possibility to a Debianer use this to.

2020-10-07 11:47 UTC, hellresistor commented on scripts/18_sshdconfig
> +  ((SCRIPT_COUNT++))
What you mean?

2020-10-07 11:49 UTC, hellresistor commented on ubuntu.sh
> +  for pre_require in $REQUIREDPROGS; do
same answer later about Debian.

2020-10-07 11:53 UTC, hellresistor commented on ubuntu.sh
> +    if ! command -v "$pre_require" >/dev/null 2>&1; then
Now I am confused Between distro names, But the logic is this:
IF UBUNTU need install netools etc (will be included the w command etc etc)
else DEBIAN not need that package but other/neither.
(Or vice-versa)

This all part about Ubuntu Debian OS.

2020-10-15 06:06 UTC, hellresistor reviewed
Check All my questions. Your answer will be your wish :)

2020-10-20 22:50 UTC, hellresistor reviewed
Hope this ok

2020-10-20 23:01 UTC, hellresistor reviewed
Checked all. be ok?

2021-02-01 14:46 UTC, konstruktoid commented
Long time no see, could you rebase and I'll have a look at it again?

2021-02-22 01:08 UTC, hellresistor commented
hello. friend.
Wow. Some(big) work have done!!! I will revise soon (not promise a fix date). Ty

2021-03-06 08:25 UTC, closed without merging